.TH QUIZ 1 "2022 October 2" Riku Takeuchi "Quiz Store"

.SH NAME
quiz - stores, retrieves, inserts, and synchronizes quizzes securely

.SH SYNOPSIS
.B quiz
[ 
.I COMMAND
] [ 
.I OPTIONS
]... [ 
.I ARGS
]...

.SH DESCRIPTION

.B quiz 
is a very simple quiz store that keeps quizzes inside 
The
.B quiz
utility provides a series of commands for manipulating the quiz store,
allowing the user to add, remove, edit, synchronize, and manipulate
quizzes.

If no COMMAND is specified, COMMAND defaults to either
.B show
or
.BR ls ,
depending on the type of specifier in ARGS. Alternatively, if \fIQUIZ_STORE_ENABLE_EXTENSIONS\fP
is set to "true", and the file \fI.extensions/COMMAND.bash\fP exists inside the
quiz store and is executable, then it is sourced into the environment,
passing any arguments and environment variables. Extensions existing in a
system-wide directory, only installable by the administrator, are always enabled.

Otherwise COMMAND must be one of the valid commands listed below.

Several of the commands below rely on or provide additional functionality if
the quiz store directory is also a git repository. If the quiz store
directory is a git repository, all quiz store modification commands will
cause a corresponding git commit. Sub-directories may be separate nested git
repositories, and quiz will use the inner-most directory relative to the
current quiz. See the \fIEXTENDED GIT EXAMPLE\fP section for a detailed
description using \fBinit\fP and
.BR git (1).

The \fBinit\fP command must be run before other commands in order to initialize
the quiz store.

There is a corresponding bash completion script for use with tab completing
quiz names in
.BR bash (1).

.SH COMMANDS

.TP
\fBinit\fP
Initialize new quiz storage.
.TP
\fBls\fP \fIsubfolder\fP
List names of quizzes inside the tree at
.I subfolder
by using the
.BR tree (1)
program. This command is alternatively named \fBlist\fP.
.TP
\fBgrep\fP [\fIGREPOPTIONS\fP] \fIsearch-string\fP
Searches inside each decrypted quiz file for \fIsearch-string\fP, and displays line
containing matched string along with filename. Uses
.BR grep (1)
for matching. \fIGREPOPTIONS\fP are passed to
.BR grep (1)
as-is. (Note: the \fIGREP_OPTIONS\fP environment variable functions as well.)
.TP
\fBfind\fP \fIquiz-names\fP...
List names of quizzes inside the tree that match \fIquiz-names\fP by using the
.BR tree (1)
program. This command is alternatively named \fBsearch\fP.
.TP
\fBshow\fP \fIquiz-name\fP
Decrypt and print a quiz named \fIquiz-name\fP.
.TP
\fBinsert\fP [ \fI--echo\fP, \fI-e\fP | \fI--multiline\fP, \fI-m\fP ] [ \fI--force\fP, \fI-f\fP ] \fIquiz-name\fP
Insert a new quiz into the quiz store called \fIquiz-name\fP. This will
read the new quiz from standard in. If \fI--echo\fP or \fI-e\fP is \fInot\fP specified,
disable keyboard echo when the quiz is entered and confirm the quiz by asking
for it twice. If \fI--multiline\fP or \fI-m\fP is specified, lines will be read until
EOF or Ctrl+D is reached. Otherwise, only a single line from standard in is read. Prompt
before overwriting an existing quiz, unless \fI--force\fP or \fI-f\fP is specified. This
command is alternatively named \fBadd\fP.
.TP
\fBedit\fP \fIquiz-name\fP
Insert a new quiz or edit an existing quiz using the default text editor specified
by the environment variable \fIEDITOR\fP or using
.BR vi (1)
as a fallback. This mode makes use of temporary files for editing, but care is taken to
ensure that temporary files are created in \fI/dev/shm\fP in order to avoid writing to
difficult-to-erase disk sectors. If \fI/dev/shm\fP is not accessible, fallback to
the ordinary \fITMPDIR\fP location, and print a warning.
.TP
\fBrm\fP [ \fI--recursive\fP, \fI-r\fP ] [ \fI--force\fP, \fI-f\fP ] \fIquiz-name\fP
Remove the quiz named \fIquiz-name\fP from the quiz store. This command is
alternatively named \fBremove\fP or \fBdelete\fP. If \fI--recursive\fP or \fI-r\fP
is specified, delete quiz-name recursively if it is a directory. If \fI--force\fP
or \fI-f\fP is specified, do not interactively prompt before removal.
.TP
\fBmv\fP [ \fI--force\fP, \fI-f\fP ] \fIold-path\fP \fInew-path\fP
Renames the quiz or directory named \fIold-path\fP to \fInew-path\fP. This
command is alternatively named \fBrename\fP. If \fI--force\fP is specified,
silently overwrite \fInew-path\fP if it exists. If \fInew-path\fP ends in a
trailing \fI/\fP, it is always treated as a directory.
.TP
\fBcp\fP [ \fI--force\fP, \fI-f\fP ] \fIold-path\fP \fInew-path\fP
Copies the quiz or directory named \fIold-path\fP to \fInew-path\fP. This
command is alternatively named \fBcopy\fP. If \fI--force\fP is specified,
silently overwrite \fInew-path\fP if it exists. If \fInew-path\fP ends in a
trailing \fI/\fP, it is always treated as a directory.
.TP
\fBgit\fP \fIgit-command-args\fP...
If the quiz store is a git repository, quiz \fIgit-command-args\fP as arguments to
.BR git (1)
using the quiz store as the git repository. If \fIgit-command-args\fP is \fBinit\fP,
in addition to initializing the git repository, add the current contents of the quiz
store to the repository in an initial commit. If the git config key \fIquiz.signcommits\fP
is set to \fItrue\fP, then all commits will be signed using \fIuser.signingkey\fP or the
default git signing key. This config key may be turned on using:
.B `quiz git config --bool --add quiz.signcommits true`
.TP
\fBhelp\fP
Show usage message.
.TP
\fBversion\fP
Show version information.

.SH SIMPLE EXAMPLES

.TP
Initialize quiz store
.B zx2c4@laptop ~ $ quiz init Jason@zx2c4.com 
.br
mkdir: created directory \[u2018]/home/zx2c4/.quiz-store\[u2019] 
.br
Quiz store initialized for Jason@zx2c4.com.
.TP
List existing quizzes in store
.B zx2c4@laptop ~ $ quiz 
.br
Quiz Store
.br
\[u251C]\[u2500]\[u2500] Business 
.br
\[u2502]   \[u251C]\[u2500]\[u2500] some-silly-business-site.com 
.br
\[u2502]   \[u2514]\[u2500]\[u2500] another-business-site.net 
.br
\[u251C]\[u2500]\[u2500] Email 
.br
\[u2502]   \[u251C]\[u2500]\[u2500] donenfeld.com 
.br
\[u2502]   \[u2514]\[u2500]\[u2500] zx2c4.com 
.br
\[u2514]\[u2500]\[u2500] France 
.br
    \[u251C]\[u2500]\[u2500] bank 
.br
    \[u251C]\[u2500]\[u2500] freebox 
.br
    \[u2514]\[u2500]\[u2500] mobilephone  
.br

.br
Alternatively, "\fBquiz ls\fP".
.TP
Find existing quizzes in store that match .com
.B zx2c4@laptop ~ $ quiz find .com
.br
Search Terms: .com
.br
\[u251C]\[u2500]\[u2500] Business 
.br
\[u2502]   \[u251C]\[u2500]\[u2500] some-silly-business-site.com 
.br
\[u2514]\[u2500]\[u2500] Email 
.br
    \[u251C]\[u2500]\[u2500] donenfeld.com 
.br
    \[u2514]\[u2500]\[u2500] zx2c4.com 
.br

.br
Alternatively, "\fBquiz search .com\fP".
.TP
Show existing quiz
.B zx2c4@laptop ~ $ quiz Email/zx2c4.com 
.br
sup3rh4x3rizmynam3 
.TP
Add quiz to store
.B zx2c4@laptop ~ $ quiz insert Business/cheese-whiz-factory 
.br
Enter quiz for Business/cheese-whiz-factory: omg so much cheese what am i gonna do
.TP
Add multiline quiz to store 
.B zx2c4@laptop ~ $ quiz insert -m Business/cheese-whiz-factory 
.br
Enter contents of Business/cheese-whiz-factory and press Ctrl+D when finished: 
.br
 
.br
Hey this is my 
.br
awesome 
.br
multi 
.br
line 
.br
quizworrrrrrrrd. 
.br
^D 
.TP
Remove quiz from store
.B zx2c4@laptop ~ $ quiz remove Business/cheese-whiz-factory 
.br
rm: remove regular file \[u2018]/home/zx2c4/.quiz-store/Business/cheese-whiz-factory.txt\[u2019]? y 
.br
removed \[u2018]/home/zx2c4/.quiz-store/Business/cheese-whiz-factory.txt\[u2019]

.SH EXTENDED GIT EXAMPLE
Here, we initialize new quiz store, create a git repository, and then manipulate and sync quizzes. Make note of the arguments to the first call of \fBquiz git push\fP; consult
.BR git-push (1)
for more information.

.B zx2c4@laptop ~ $ quiz init Jason@zx2c4.com 
.br
mkdir: created directory \[u2018]/home/zx2c4/.quiz-store\[u2019] 
.br
Quiz store initialized for Jason@zx2c4.com. 

.B zx2c4@laptop ~ $ quiz git init 
.br
Initialized empty Git repository in /home/zx2c4/.quiz-store/.git/

.B zx2c4@laptop ~ $ quiz git remote add origin kexec.com:quiz-store 

.B zx2c4@laptop ~ $ quiz insert Amazon/amazonemail@email.com
.br
Enter answer for Amazon/amazonemail@email.com:
.br
1 file changed, 0 insertions(+), 0 deletions(-) 
.br
create mode 100644 Amazon/amazonemail@email.com.txt 

.B zx2c4@laptop ~ $ quiz git push -u --all
.br
Counting objects: 4, done. 
.br
Delta compression using up to 2 threads. 
.br
Compressing objects: 100% (3/3), done. 
.br
Writing objects: 100% (4/4), 921 bytes, done. 
.br
Total 4 (delta 0), reused 0 (delta 0) 
.br
To kexec.com:quiz-store 
.br
* [new branch]      master -> master 
.br
Branch master set up to track remote branch master from origin. 

.B zx2c4@laptop ~ $ quiz insert Amazon/otheraccount@email.com 
.br
Enter quiz for Amazon/otheraccount@email.com: som3r3a11yb1gp4ssw0rd!!88** 
.br
[master b9b6746] Added given quiz for Amazon/otheraccount@email.com to store. 
.br
1 file changed, 0 insertions(+), 0 deletions(-) 
.br
create mode 100644 Amazon/otheraccount@email.com.txt 

.B zx2c4@laptop ~ $ quiz rm Amazon/amazonemail@email.com 
.br
rm: remove regular file \[u2018]/home/zx2c4/.quiz-store/Amazon/amazonemail@email.com.txt\[u2019]? y 
.br
removed \[u2018]/home/zx2c4/.quiz-store/Amazon/amazonemail@email.com.txt\[u2019] 
.br
rm 'Amazon/amazonemail@email.com.txt' 
.br
[master 288b379] Removed Amazon/amazonemail@email.com from store. 
.br
1 file changed, 0 insertions(+), 0 deletions(-) 
.br
delete mode 100644 Amazon/amazonemail@email.com.txt 

.B zx2c4@laptop ~ $ quiz git push
.br
Counting objects: 9, done. 
.br
Delta compression using up to 2 threads. 
.br
Compressing objects: 100% (5/5), done. 
.br
Writing objects: 100% (7/7), 1.25 KiB, done. 
.br
Total 7 (delta 0), reused 0 (delta 0) 
.br
To kexec.com:quiz-store

.SH FILES

.TP
.B ~/.quiz-store
The default quiz storage directory.
.TP
.B ~/.quiz-store/.extensions
The directory containing extension files.

.SH ENVIRONMENT VARIABLES

.TP
.I QUIZ_STORE_DIR
Overrides the default quiz storage directory.
.TP
.I QUIZ_STORE_UMASK
Sets the umask of all files modified by quiz, by default \fI077\fP.
.TP
.I QUIZ_STORE_ENABLE_EXTENSIONS
This environment variable must be set to "true" for extensions to be enabled.
.TP
.I QUIZ_STORE_EXTENSIONS_DIR
The location to look for executable extension files, by default
\fIQUIZ_STORE_DIR/.extensions\fP.
.TP
.I EDITOR
The location of the text editor used by \fBedit\fP.
.SH SEE ALSO
.BR tr (1),
.BR git (1),

.SH AUTHOR
.B quiz
was written by
.MT Jason@zx2c4.com
Jason A. Donenfeld
.ME .
For updates and more information, a project page is available on the
.UR https://github.com/rikuson/quiz/
World Wide Web
.UE .

.SH COPYING
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
